theme:
  name: "material"

site_name: GarpixCMS

plugins:
- search
- mkdocstrings

nav:
  - Быстрый старт: index.md
  - Установка:
    - Установка зависимостей: install_deps.md
    - Создание нового проекта: install_new_project.md
    - Запускаем проект: install_start_project.md
  - Примеры:
    - Простой корпорат на шаблонах: example_simple_templates_site.md
    - Вход по логину/паролю: example_simple_auth.md
    - Уведомления (Email, SMS, PUSH и другие): example_notify.md
  - Пакеты: packages.md
  - Утилиты: utils.md
  - FAQ:
    - CORS: faq_cors.md
    - Создание своего пакета: faq_pack.md
